### ISSUE TITLE
Ajustes da Ementa no MODULO 3

### ISSUE THREAD

**Issue by osvaldoabel** [Webschool-io/Curso-PHP-Completo#4]
Estou preparando um PR para esse módulo, porém dei uma olhada na Ementa, e gostaria de sugerir essa extrutura/tópicos para o módulo 3. 
### MODULO 3 - BANCO DE DADOS
- Introdução a Banco de Dados
  - Linguagem SQL. 
  - Mysql
  - Postgresql
  - MongoDB
- PHP com MySQL 
- PHP com PostgreSQL

**Comment by vagkaefer** [comment]
Alterações realizadas através de PR! ;D

**Comment by vagkaefer** [comment]
Obrigado pela contribuição Kanguanda
